-- Additional data for Lecturer table
INSERT INTO Lecturer (Name, Department_ID) VALUES
-- Department 1: Computer Science
('Dr. Thompson', 1),
('Prof. Martinez', 1),
('Dr. Robinson', 1),
('Prof. Clark', 1), 
('Dr. Rodriguez', 1), 
('Prof. Lewis', 1), 
('Dr. Lee', 1), 
('Prof. Walker', 1), 
('Dr. Hall', 1), 
('Prof. Allen', 1), 
('Dr. Young', 1),
('Prof. King', 1), 
('Dr. Wright', 1), 
('Prof. Scott', 1), 
('Dr. Green', 1),
('Prof. Adams', 1), 
('Dr. Baker', 1), 
('Prof. Gonzalez', 1), 
('Dr. Nelson', 1), 
('Prof. Carter', 1), 

-- Department 2: Engineering
('Dr. Thompson', 2),
('Prof. Martinez', 2),
('Dr. Robinson', 2),
('Prof. Clark', 2),
('Dr. Rodriguez', 2),
('Prof. Lewis', 2),
('Dr. Lee', 2),
('Prof. Walker', 2),
('Dr. Hall', 2),
('Prof. Allen', 2),
('Dr. Young', 2),
('Prof. King', 2),
('Dr. Wright', 2),
('Prof. Scott', 2),
('Dr. Green', 2),
('Prof. Adams', 2),
('Dr. Baker', 2),
('Prof. Gonzalez', 2),
('Dr. Nelson', 2),
('Prof. Carter', 2),

-- Department 3: Law
('Dr. Thompson', 3),
('Prof. Martinez', 3),
('Dr. Robinson', 3),
('Prof. Clark', 3),
('Dr. Rodriguez', 3),
('Prof. Lewis', 3),
('Dr. Lee', 3),
('Prof. Walker', 3),
('Dr. Hall', 3),
('Prof. Allen', 3),
('Dr. Young', 3),
('Prof. King', 3),
('Dr. Wright', 3),
('Prof. Scott', 3),
('Dr. Green', 3),
('Prof. Adams', 3),
('Dr. Baker', 3),
('Prof. Gonzalez', 3),
('Dr. Nelson', 3),
('Prof. Carter', 3),

-- Department 4: Business
('Dr. Thompson', 4),
('Prof. Martinez', 4),
('Dr. Robinson', 4),
('Prof. Clark', 4),
('Dr. Rodriguez', 4),
('Prof. Lewis', 4),
('Dr. Lee', 4),
('Prof. Walker', 4),
('Dr. Hall', 4),
('Prof. Allen', 4),
('Dr. Young', 4),
('Prof. King', 4),
('Dr. Wright', 4),
('Prof. Scott', 4),
('Dr. Green', 4),
('Prof. Adams', 4),
('Dr. Baker', 4),
('Prof. Gonzalez', 4),
('Dr. Nelson', 4),
('Prof. Carter', 4);



-- Additional data for Tutor table
INSERT INTO Tutor (Name, Department_ID) VALUES
-- Department 1: Computer Science
('Frank', 1),
('Grace', 1), 
('Hannah', 1), 
('Isaac', 1), 
('Julia', 1), 
('Kevin', 1),
('Laura', 1),
('Michael', 1),
('Nina', 1), 
('Oscar', 1), 
('Paul', 1), 
('Quinn', 1), 
('Rachel', 1), 
('Sam', 1), 
('Tina', 1), 
('Uma', 1), 
('Victor', 1), 
('Wendy', 1), 
('Xander', 1), 
('Yara', 1), 

-- Department 2: Engineering
('Frank', 2), 
('Grace', 2), 
('Hannah', 2),
('Isaac', 2), 
('Julia', 2),
('Kevin', 2),
('Laura', 2),
('Michael', 2), 
('Nina', 2),
('Oscar', 2),
('Paul', 2), 
('Quinn', 2),
('Rachel', 2),
('Sam', 2),
('Tina', 2),
('Uma', 2),
('Victor', 2),
('Wendy', 2),
('Xander', 2),
('Yara', 2),

-- Department 3: Law
('Frank', 3),
('Grace', 3),
('Hannah', 3),
('Isaac', 3),
('Julia', 3),
('Kevin', 3),
('Laura', 3),
('Michael', 3),
('Nina', 3),
('Oscar', 3),
('Paul', 3),
('Quinn', 3),
('Rachel', 3),
('Sam', 3),
('Tina', 3),
('Uma', 3),
('Victor', 3),
('Wendy', 3),
('Xander', 3),
('Yara', 3),

-- Department 4: Business
('Frank', 4),
('Grace', 4),
('Hannah', 4),
('Isaac', 4),
('Julia', 4),
('Kevin', 4),
('Laura', 4),
('Michael', 4),
('Nina', 4),
('Oscar', 4),
('Paul', 4),
('Quinn', 4),
('Rachel', 4),
('Sam', 4),
('Tina', 4),
('Uma', 4),
('Victor', 4),
('Wendy', 4),
('Xander', 4),
('Yara', 4);
